CREATE TABLE alunos (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome CHARACTER(20) NOT NULL,
    idade INTEGER NOT NULL
);

CREATE TABLE cursos (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome CHARACTER(20) NOT NULL
);

CREATE TABLE turmas (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome CHARACTER(20) NOT NULL
);

CREATE TABLE professores (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome CHARACTER(20) NOT NULL,
    sobrenome CHARACTER(20) NOT NULL,
    idade INTEGER NOT NULL,
    especialidade CHARACTER(20)
);